config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :likes, only: [:create, :destroy]
  resources :tags
  resources :prototypes do
    resources :comments, only: [:new, :create]
  end
  root 'prototypes#index'
end

app/models/captured_image.rb
class CapturedImage < ActiveRecord::Base
  belongs_to :prototype

  mount_uploader :name, CapturedImageUploader

  enum status: [:main, :sub]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :prototype

  validates :text, presence: true
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :user
  belongs_to :prototype, counter_cache: :likes_count
end

app/models/prototype.rb
class Prototype < ActiveRecord::Base
  has_many :captured_images, dependent: :delete_all
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  belongs_to :user

  validates :title, :copy, :concept, :captured_images, presence: true

  accepts_nested_attributes_for :captured_images, reject_if: :reject_captured_image

  acts_as_taggable_on :tags

  def reject_captured_image(attributed)
    attributed['name'].blank?
  end

  def main_image
    captured_images.main.first.name
  end

  def sub_images
    captured_images.sub
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :prototypes
  has_many :comments
  has_many :likes

  mount_uploader :avatar, CapturedImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  add_flash_types :success, :info, :warning, :danger

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << [:name, :profile, :work, :group, :avatar]
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    prototype = Prototype.find(params[:prototype_id])
    prototype.comments.create(comment_params)
    @comments = prototype.comments
  end

  private
  def comment_params
    params.require(:comment).permit(:text, :user_id)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController

  before_action :set_prototype, only: [:create]

  def create
    @prototype.likes.create(like_params)
  end

  def destroy
    Like.find_by(prototype_id: params[:id], user_id: current_user.id).destroy
    @prototype = Prototype.find(params[:id])
  end

  private
  def set_prototype
    @prototype = Prototype.find(params[:prototype_id])
  end

  def like_params
    params.permit(:prototype_id).merge(user_id: current_user.id)
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController

  before_action :set_prototype, only: [:show, :edit, :update, :destroy]
  def index
    @prototypes = Prototype.order(created_at: :desc).page(params[:page])
  end

  def new
    @prototype = Prototype.new
    @prototype.captured_images.build
  end

  def create
    prototype = current_user.prototypes.new(prototype_params)
    if prototype.save
      redirect_to root_path, success: "Successfully created your prototype."
    else
      redirect_to new_prototype_path, warning: "Unfortunately failed to create."
    end
  end

  def show
    @comment = current_user.comments.new
    @comments = @prototype.comments
  end

  def edit
  end

  def update
    if @prototype.update(update_params)
      redirect_to prototype_path(@prototype), success: "Successfully updated your prototype."
    else
      redirect_to edit_prototype_path, warning: "Unfortunately failed to update."
    end
  end

  def destroy
    @prototype.destroy
  end

  private
  def prototype_params
    tag_list = params[:prototype][:tag_list]
    params.require(:prototype).permit(:title, :copy, :concept, captured_images_attributes: [:name, :status]).merge(tag_list: tag_list)
  end

  def update_params
    tag_list = params[:prototype][:tag_list]
    params.require(:prototype).permit(:title, :copy, :concept, captured_images_attributes: [:id, :name, :status]).merge(tag_list: tag_list)
  end

  def set_prototype
    @prototype = Prototype.find(params[:id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    @tags = ActsAsTaggableOn::Tag.most_used
  end

  def show
    @prototypes = Prototype.tagged_with(params[:id]).page(params[:page])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only: [:show]

  def show
  end


  private
  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/create.js.erb
$('#comment_text').val('');
$('#comment_list').html(
  '<%= j(render partial: "prototypes/comment", collection: @comments) %>'
);
$('#num').html('(<%= @comments.count %>)');

app/views/common/_view_tag_button.html.haml
= link_to "View Tags", tags_path, class: "btn btn-default col-lg-1"

app/views/layouts/_footer.html.haml
.container
  %footer
    %p &copy; PROTO SPACE 2015.

app/views/layouts/_header.html.haml
.navbar.navbar-default.navbar-static-top.navbar-fixed-top
  .container
    %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    %a.navbar-brand(href="/")
      = image_tag("logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "36px")
    .navbar-collapse.collapse.navbar-responsive-collapse
      //not login
      %ul.nav.navbar-nav.navbar-right
        %li
          .btn.btn-primary.navbar-btn
            %a{ href: new_user_session_path }
              Get Started
      //login
      %ul.nav.navbar-nav.navbar-right
        %li.dropdown
          %a.dropdown-toggle{ "aria-expanded" => "false", "data-toggle" => "dropdown", href: "#", role: "button" }
            - if user_signed_in?
              = current_user.name
            - else
              noname
            %span.caret
          %ul.dropdown-menu{ role: "menu" }
            - if current_user
              %li
                = link_to 'My Page', user_path(current_user)
              %li
                = link_to 'Profile Edit', edit_user_path(current_user)
              %li
                = link_to 'Logout', destroy_user_session_path, method: "delete"
            - else
              %li
                = link_to 'Login', new_user_session_path
        %li
          .btn.btn-primary.navbar-btn
            %a{ href: "/prototypes/new" }
              New Proto

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Protospace
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = render "layouts/header"
    - flash.each do |key, value|
      - key = "info" if key == "notice"
      - ket = "danger" if key == "alert"
      = content_tag :div, value, class: "alert alert-#{key}"
    = yield
    = render "layouts/footer"

app/views/likes/_like.html.haml
.col-md-6.text-right
  %button.btn.btn-default
    - if current_user.likes.exists?(prototype_id: @prototype.id)
      = link_to image_tag("heart_red.svg"), like_path(@prototype), method: :delete, remote: true
    - else
      = link_to image_tag("icon_heart.svg"), likes_path(prototype_id: @prototype.id), method: :post, remote: true
    Like
    %span#likes-num
      = @prototype.likes_count

app/views/likes/create.js.erb
$('#likes-area').html('<%= j(render partial: "likes/like") %>');

app/views/likes/destroy.js.erb
$('#likes-area').html('<%= j(render partial: "likes/like") %>');

app/views/prototypes/_comment.html.haml
.media
  .media-left
    %a{ href: user_path(comment.user) }
      = image_tag(comment.user.avatar, class: "media-object", alt: comment.user.name, style: "width: 64px; height: 64px;", "data-holder-rendered" => "true", "data-src" => "holder.js/64x64")
  .media-body
    %h4#top-aligned-media.media-heading
      = comment.user.name
      %a.anchorjs-link{ href: user_path(comment.user) }
        %span.anchorjs-icon
    %p
      = comment.text
      

app/views/prototypes/_prototype.html.haml
.col-sm-4.col-md-3.proto-content
  .thumbnail
    = link_to prototype_path(prototype) do
      = image_tag(prototype.captured_images.main.first.name)
      .caption
        %h3
          = prototype.title
        .proto-meta
          .proto-user
            = link_to user_path(prototype.user) do
              = "by " + prototype.user.name
          .proto-posted
            Apr 26
        %ul.proto-tag-list.list-inline
          = render partial: "prototypes/tag", collection: prototype.tag_list

app/views/prototypes/_tag.html.haml
%li
  = link_to tag, tag_path(tag), class: "btn btn-default"

app/views/prototypes/destroy.js.erb
$('.proto-content').html(
  '<%= j(render partial: "users/prototype", collection: current_user.prototypes) %>'
  );
$('.navbar').after(
  '<div class="alert alert-success">Successfully deleted your prototype.</div>'
  );
$('.project-number').html(
  '<%= current_user.prototypes.count %><i>Projects</i>'
  );

app/views/prototypes/edit.html.haml
= form_for(@prototype, html: { class: "container proto-new" }) do |f|
  .col-md-8.col-md-offset-2
    %header.row.user-nav.row
      .col-sm-12
        = f.text_field :title, class: "proto-new-title", placeholder: "Title"
    .row
      .col-sm-12
        .cover-image-upload
          = f.fields_for :captured_images, @prototype.captured_images.main do |captured_image|
            = captured_image.file_field :name
            = captured_image.hidden_field :status, value: :main
      .col-sm-12
        %ul.proto-sub-list.list-group
          - @prototype.captured_images.sub.each do |image|
            %li.list-group-item.col-md-4
              .image-upload
                = f.fields_for :captured_images, image do |captured_image|
                  = captured_image.file_field :name
                  = captured_image.hidden_field :status, value: :sub
          %li.list-group-item.col-md-4
            .image-upload-plus
              %span +
    .row.proto-description
      .col-sm-12
        = f.text_field :copy, placeholder: "Catch Copy"
      .col-sm-12
        = f.text_area :concept, cols: "30", rows: "4", placeholder: "Concept"
      .col-sm-12
        %h4 Tag List
        .row
          .col-sm-3
            = text_field_tag 'prototype[tag_list][]', "#{@prototype.tag_list[0]}", placeholder: "Web Design"
          .col-sm-3
            = text_field_tag 'prototype[tag_list][]', "#{@prototype.tag_list[1]}", placeholder: "UI"
          .col-sm-3
            = text_field_tag 'prototype[tag_list][]', "#{@prototype.tag_list[2]}", placeholder: "Application"
    .row.text-center.proto-btn
      = f.submit "Publish", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/index.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{ role: "presentation" }
          %a{ href: "#" } Popular PROTO
        %li{ role: "presentation" }
          %a{ href: "#" } Newest PROTO
      = render partial: "common/view_tag_button"

.container.proto-list
  .row
    - if @prototypes
      = render @prototypes
    - else
      nothing

.text-center
  %ul.pagination
    = paginate @prototypes

app/views/prototypes/new.html.haml
= form_for(@prototype, html: { class: "container proto-new" }) do |f|
  .col-md-8.col-md-offset-2
    %header.row.user-nav.row
      .col-sm-12
        = f.text_field :title, class: "proto-new-title", placeholder: "Title"
    .row
      .col-sm-12
        .cover-image-upload
          = f.fields_for :captured_images do |captured_image|
            = captured_image.file_field :name
            = captured_image.hidden_field :status, value: :main
      .col-sm-12
        %ul.proto-sub-list.list-group
          - 2.times do
            %li.list-group-item.col-md-4
              .image-upload
                = f.fields_for :captured_images do |captured_image|
                  = captured_image.file_field :name
                  = captured_image.hidden_field :status, value: :sub
          %li.list-group-item.col-md-4
            .image-upload-plus
              %span +
    .row.proto-description
      .col-sm-12
        = f.text_field :copy, placeholder: "Catch Copy"
      .col-sm-12
        = f.text_area :concept, cols: "30", rows: "4", placeholder: "Concept"
      .col-sm-12
        %h4 Tag List
        .row
          .col-sm-3
            = text_field_tag 'prototype[tag_list][]', "", placeholder: "Web Design"
          .col-sm-3
            = text_field_tag 'prototype[tag_list][]', "", placeholder: "UI"
          .col-sm-3
            = text_field_tag 'prototype[tag_list][]', "", placeholder: "Application"
    .row.text-center.proto-btn
      = f.submit "Publish", class: "btn btn-lg btn-primary btn-block"

app/views/prototypes/show.html.haml
.container.proto-page
  %header.row.user-nav
    .col-md-6
      .media
        .media-left
          = link_to user_path(@prototype.user) do
            = image_tag(@prototype.user.avatar, alt: "#{@prototype.user.name}", "data-holder-rendered" => "true", "data-src" => "holder.js/64x64", class: "media-object", style: "width: 64px; height: 64px;")
        .media-body
          %h4#top-aligned-media.media-heading
            = @prototype.title
          .proto-user
            = link_to "by " + @prototype.user.name, user_path(@prototype.user)
            %span.degree
              = @prototype.user.group
              = @prototype.user.work
    #likes-area
      = render partial: 'likes/like'
  .row
    .col-md-9
      = image_tag(@prototype.main_image, class: 'img-responsive')
    .col-md-3
      %ul.proto-sub-list.list-group
        - @prototype.sub_images.each do |image|
          %li.list-group-item
            = image_tag(image.name, class: 'img-responsive')
  .row.proto-description
    .col-md-3
      %h4 Catch Copy
      %p
        = @prototype.copy
    .col-md-6
      %h4 Concept
      %p
        = @prototype.concept
    .col-md-3
      %h4 Tag List
      %ul.proto-tag-list.list-inline
        = render partial: "tag", collection: @prototype.tags
  .row.proto-comments
    %h4.col-md-12
      Comments
      %span#num
        = "(#{@comments.count})"
    .col-md-8
      #comment_list
        = render partial: "prototypes/comment", collection: @comments
      = form_for([@prototype, @comment], remote: true, html: { class: "form-inline", role: "form" }) do |f|
        %h4 Write a comment
        .row
          .form-group.col-md-10
            = f.hidden_field :user_id, value: current_user.id
            = f.text_area :text, placeholder: "Your comments", rows: "3", class: "form-control"
          .form-group.col-md-2
            = f.submit "Comment", class: "button btn btn-primary"

app/views/tags/index.html.haml
.container
  .row
    .tags-list
      %h2 Tags list
      %ul
        - @tags.each do |tag|
          %li.col-md-4
            = link_to tag, tag_path(tag.name), class: "btn btn-default"

app/views/tags/show.html.haml
.jumbotron
  .container.text-center
    = image_tag("header_logo.png", alt: "PROTO TYPE - SHARE THE PROTOTYPE", height: "73px")

.filter-nav
  .container
    .row
      %ul.nav.nav-pills.col-lg-11
        %li.active{ role: "presentation" }
          %a{ href: "#" } Popular PROTO
        %li{ role: "presentation" }
          %a{ href: "#" } Newest PROTO
      = render partial: "common/view_tag_button"

.container.proto-list
  .row
    - if @prototypes
      = render @prototypes
    - else
      nothing

.text-center
  %ul.pagination
    = paginate @prototypes

app/views/users/_prototype.html.haml
.col-sm-4.col-md-3.proto-content
  .dropdown.drop_menu_location
    = button_tag "Action", class: "btn btn-default dropdown-toggle", id: "dropdownMenu", "data-toggle" => "dropdown", "aria-expanded" => "true", type: "button"
    %ul.dropdown-menu{"aria-labelledby" => "dropdownMenu1"}
      %li
        = link_to "Delete", prototype_path(prototype), method: :delete, remote: true
      %li
        = link_to "Edit", edit_prototype_path(prototype)
  .thumbnail
    - if prototype.captured_images
      = link_to image_tag(prototype.captured_images[0].name), prototype_path(prototype)
    - else
      = link_to image_tag("no_image.png"), prototype_path(prototype)
    .caption
      %h3
        = prototype.title
      .proto-meta
        .proto-date
          Apr 26
      %ul.proto-tag-list.list-inline
        %li
          %a{:href => "#", :class => "btn btn-default"} iPad
        %li
          %a{:href => "#", :class => "btn btn-default"} wireframe

app/views/users/show.html.haml
.container.user-page
  %header.user-nav
    .media
      .media-left
        %a{:href => "#"}
          = image_tag(current_user.avatar, alt: "", "data-holder-rendered" => "true", "data-src" => "holder.js/64x64", style: "width: 64px; height: 64px;", class: "media-object")
      .media-body
        %h4#top-aligned-media.media-heading
          Top aligned media
          %span.label.label-default.project-number
            = current_user.prototypes.count
            %i Projects
        .proto-user
          %span.degree
            = current_user.group
            = current_user.work
        .row
          .col-md-6
            %h4 Profile
            %p
              = current_user.profile
          .col-md-6
            %h4 Works
            %p
              = current_user.work
.container.proto-list
  .row
    = render partial: "users/prototype", collection: current_user.prototypes


.text-center
  %ul.pagination
    = paginate @prototypes